Post release check
LNP-BP/rgb-sdk pull request #10
Opened 2020-10-22 13:47 UTC by zoedberg

closes #8

2020-10-22 19:08 UTC, dr-orlovsky requested changes
Everything looks great except one small Cargo.toml issue with rgb_node dependency

2020-10-22 19:08 UTC, dr-orlovsky commented on rust-lib/Cargo.toml
> +rgb_node = { git = "https://github.com/LNP-BP/rgb-node", version = "~0.1.0" }
We do not need git here at all
```suggestion
rgb_node = "~0.1.0"
```

2020-10-23 08:13 UTC, zoedberg commented on rust-lib/Cargo.toml
> +rgb_node = { git = "https://github.com/LNP-BP/rgb-node", version = "~0.1.0" }
Sorry, I misunderstood, fixed it

2020-10-23 09:05 UTC, dr-orlovsky approved these changes

2020-10-23 09:05 UTC, merged